-- MIGRATION: ADD OPTIONAL BUSINESS NAME FIELD & INITIAL PROFILE UPDATE ELIGIBILITY
-- Run this SQL in your Supabase Dashboard -> SQL Editor.

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS business_name VARCHAR(25);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS has_updated_profile BOOLEAN DEFAULT FALSE;
